file(GLOB_RECURSE HEADER_PATHS "${SOURCE_FOLDER}/*.h" "${SOURCE_FOLDER}/*.hpp")
foreach(HEADER_PATH ${HEADER_PATHS})
    file(RELATIVE_PATH RELATIVE_HEADER "${SOURCE_FOLDER}" "${HEADER_PATH}")
    get_filename_component(DESTINATION_FILE "${DESTINATION_FOLDER}/${RELATIVE_HEADER}" DIRECTORY)

    file(INSTALL "${HEADER_PATH}" DESTINATION "${DESTINATION_FILE}")
endforeach()
