file(GLOB_RECURSE HEADERS "${SOURCE_FOLDER}/*.h" "${SOURCE_FOLDER}/*.hpp")
foreach(HEADER ${HEADERS})
    file(RELATIVE_PATH RELATIVE_HEADER "${SOURCE_FOLDER}" "${HEADER}")
    get_filename_component(DESTINATION_FILE "${INSTALL_FOLDER}/${RELATIVE_HEADER}" DIRECTORY)

    file(INSTALL "${HEADER}" DESTINATION "${DESTINATION_FILE}")
endforeach()
