if(EXANITE_EXTERNAL_PROJECT_CONFIG_INCLUDED)
    return()
endif()
set(EXANITE_EXTERNAL_PROJECT_CONFIG_INCLUDED TRUE)

set(EXANITE_EXTERNAL_PROJECT_ARGS
    "-DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}"
    "-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}"
)
