if(NOT TARGET Exanite::VulkanMemoryAllocator-Headers)
    add_library(VulkanMemoryAllocator-Headers INTERFACE)
    add_library(Exanite::VulkanMemoryAllocator-Headers ALIAS VulkanMemoryAllocator-Headers)
    target_include_directories(VulkanMemoryAllocator-Headers INTERFACE ${CMAKE_CURRENT_LIST_DIR}/../native/VulkanMemoryAllocator/include)
endif()
